In [6]:
#import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
# importing dataset

dataset = pd.read_csv('Data.csv')
x= dataset.iloc[:,:3].values
y= dataset.iloc[:,3].values


In [8]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [9]:
# completing missing data

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan,strategy='mean')
x[:,1:3] = imputer.fit_transform(x[:,1:3])
#imputer = imputer.fit(x[:,1:3])
#x[:,1:3] = imputer.transform(x[:,1:3])


In [10]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [11]:
# encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x = LabelEncoder()
labelencoder_y = LabelEncoder()
x[:,0 ]=labelencoder_x.fit_transform(x[:,0])
y=labelencoder_y.fit_transform(y)
onehotencoder = OneHotEncoder(categorical_features =[0])
x = onehotencoder.fit_transform(x).toarray()
print(x[:,:3])
print(y)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
[0 1 0 0 1 1 0 1 0 1]


E:\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
E:\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [12]:

# spliting dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [13]:
print(y_train)
print(y_test)

[1 1 1 0 1 0 0 1]
[0 0]


In [14]:
# Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [37]:
print(x_train[:,1:])

[[ 2.64575131 -0.77459667  0.26306757  0.12381479]
 [-0.37796447 -0.77459667 -0.25350148  0.46175632]
 [-0.37796447  1.29099445 -1.97539832 -1.53093341]
 [-0.37796447  1.29099445  0.05261351 -1.11141978]
 [-0.37796447 -0.77459667  1.64058505  1.7202972 ]
 [-0.37796447  1.29099445 -0.0813118  -0.16751412]
 [-0.37796447 -0.77459667  0.95182631  0.98614835]
 [-0.37796447 -0.77459667 -0.59788085 -0.48214934]]
