In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("Data.csv")
x = df.iloc[:,:3].values
y = df.iloc[:,3].values
print(f"{x} , {y}")

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]] , ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [3]:
from sklearn.impute import SimpleImputer # to Impute the NAN (non-Exciting Data in x)
imputer = SimpleImputer(missing_values=np.nan,strategy='mean') # We gonna impute the NAN values by calculationg the mean value of the Salary column
x[:,1:] = imputer.fit_transform(x[:,1:]) # imputing the NAN values in columns 1, 2
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [4]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder # encoding the Strings into Numbers EX: ("Egypt","KSA") --> (0,1)
x[:,0] = LabelEncoder().fit_transform(x[:,0]) # x[:,0] = [0 2 1 2 1 0 2 0 1 0]
y[:] = LabelEncoder().fit_transform(y[:])  # y = [0 1 0 0 1 1 0 1 0 1]

In [5]:
from sklearn.model_selection import train_test_split #so we can split the data to data_train and data_test
x_train , x_test , y_train , y_test = train_test_split(x, y, test_size= 0.2, random_state=0) # Spliting the data fifth of the data is Test set and the reamining is the Training set
print(f"train = {x_train} , {y_train}\n ,test = {x_test} , {y_test}")

train = [[1 40.0 63777.77777777778]
 [0 37.0 67000.0]
 [2 27.0 48000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [2 38.0 61000.0]
 [0 44.0 72000.0]
 [0 35.0 58000.0]] , [1 1 1 0 1 0 0 1]
 ,test = [[1 30.0 54000.0]
 [1 50.0 83000.0]] , [0 0]
